apiVersion: dp.wso2.com/v1alpha1
kind: RateLimitPolicy
metadata:
  name: free-tier-runtime-low-traffic
spec:
  override:
    custom:
      key: free_tier_run_time_low_traffic
      requestsPerUnit: 2
      unit: Minute
      organization: default
  targetRef:
    kind: Gateway
    name: default
    group: gateway.networking.k8s.io